---
title: "Project 2"
author: "James Spalding, Ryan Winder"
date: "2024-04-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include = F)

#Libraries
library(tidyverse)
library(readxl)
library(DescTools)
library(gt)
library(gtExtras)
library(gridExtra)
library(ggpubr)
```

```{r}
data = read.csv("CervicalCancer.csv") %>% select(-"STDs.AIDS") #None of the patients had AIDS
```

## Introduction

## Exploring the Data

```{r, include = T}
##### Summary Stats Table #####

Term       = c("Age",
               "Number of sexual partners",
               "Age of first sexual intercourse", 
               "Number of Pregnancies",
               "Smoke",
               "Years of Smoking",
               "Packs Smoked/Year",
               "Hormonal Contraceptives", 
               "Years used Hormonal Contraceptives",
               "IUD",
               "Years used IUD",
               "Has had STD",
               "Condylomatosis", 
               "Syphilis",
               "Pelvic Inflammatory Disease",
               "Genital Herpes",
               "Molluscum Contagiosum",
               "HIV",
               "Hepatitis B",
               "HPV",
               "Positive for Cervical Cancer")

Ratio = c()
Count = c()
Mean = c()
Min = c()
Max = c()
SD = c()

#Obtain descriptive stats
for(i in names(data)){
  #Determine if percent or mean is applicable
  if (length(unique(data[[i]])) == 2){
    Ratio = c(Ratio, paste0(round(mean(data[[i]]),4) * 100, "%"))
    Count = c(Count, length(which(data[[i]] == 1)))
    Mean  = c(Mean, "")
    Min   = c(Min, "")
    Max   = c(Max, "")
    SD    = c(SD, "")
  }else{
    Ratio = c(Ratio, "")
    Count = c(Count, "")
    Mean  = c(Mean, round(mean(data[[i]]),2))
    Min   = c(Min, min(data[[i]]))
    Max   = c(Max, max(data[[i]]))
    SD    = c(SD, round(sd(data[[i]]),2))
  }
}

#Decided to split into 2 types for better presentation...

#Binary variables
binTerm = Term[c(5,8,10,12:21)]
Percentage = Ratio[c(5,8,10,12:21)]
Count = Count[c(5,8,10,12:21)]

#Quantitative variables
quantTerm = c(Term[c(1:4, 6,7,9)], rep("",6))
Mean = c(Mean[c(1:4, 6,7,9)], rep("",6))
Min  = c(Min[c(1:4, 6,7,9)], rep("",6))
Max  = c(Max[c(1:4, 6,7,9)], rep("",6))
SD   = c(SD[c(1:4, 6,7,9)], rep("",6))


records = as.data.frame(t(as.data.frame(rbind(binTerm, Count, Percentage,
                                              quantTerm, Mean, Min, Max, SD))))

records %>%
  gt() %>%
  gt_theme_nytimes() %>%
  tab_header(title="Table 1: Variables explained.") %>%
  tab_spanner(label="Binary Terms", columns = c(binTerm, Count, Percentage)) %>%
  tab_spanner(label="Quantitative Terms", columns = c(quantTerm, Mean, Min, Max, SD)) %>%
  cols_label(binTerm = " ", quantTerm = " ")



```



## Statistical Methods

```{r}
difference_function <- function(x, test_to_run = mean) {
  
  function_list <- list(
    Cancer = c(x[Biopsy == 1]),
    No_Cancer = c(x[Biopsy == 0])
  )
  
  
  dat1 <- function_list$Cancer
  dat2 <- function_list$No_Cancer
  
  m=length(function_list$Cancer)
  n=length(function_list$No_Cancer)
  tot=m+n
  Dobs=test_to_run(dat1)-test_to_run(dat2)

  nperm=1000
  Dperm=rep(0,nperm)
  alldat=c(dat1,dat2)

  for(i in 1:nperm){
    index=sample(1:tot,m)
    newdat1=alldat[index]
    newdat2=alldat[-index]
    Dperm[i]=test_to_run(newdat1)-test_to_run(newdat2)
  }

  pvalue=sum(abs(Dperm)>=abs(Dobs))/nperm
  pvalue
}

to_test <- c(2,3,4,6,7,9,11)

#to_test <- c(data$Number.of.sexual.partners,data$First.sexual.intercourse,data$Num.of.pregnancies,
#             data$Smokes..years.,data$Smokes..packs.year.,data$Hormonal.Contraceptives..years.,
#             data$IUD..years.)

p_values_mean <- c()
p_values_var <- c()
p_values_median <- c()

for(i in length(to_test)) {
  p_values_mean[i] <- difference_function(to_test[i])
  p_values_var[i] <- difference_function(to_test[i], var)
  p_values_median[i] <- difference_function(to_test[i], median)
}

explanatory_variables <- c("Number of sexual partners","Age of first sexual intercourse","Num of pregnancies",
                           "Years smoking", "Packs smoked a year", "Years using Hormonal Contraceptives",
                           "Years using IUD")

permutation_tests <- data.frame(
  Variable = explanatory_variables$variables,
  Pval_mean = p_values_mean,
  Pval_var = p_values_var,
  Pval_median = p_values_median
)

permutation_tests %>%
  gt() %>%
  gt_theme_nytimes() %>%
  tab_header(title="Table : Probabilities of Two-Sample Permutation Tests")

head(data)
```



## Results

## Conclusion